include: all_rules.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/lib/l10n/**"
  strong-mode:
    implicit-dynamic: false
    implicit-casts: false
  errors:
    included_file_warning: ignore

# COMMENT

linter:
  rules:
    # Conflicts
    unnecessary_final: false
    prefer_double_quotes: false
    prefer_single_quotes: false
    always_specify_types: false

    # Misc
    empty_catches: false
    public_member_api_docs: false
    prefer_relative_imports: false
    always_use_package_imports: false
    lines_longer_than_80_chars: false
    avoid_annotating_with_dynamic: false
    avoid_print: false
    diagnostic_describe_all_properties: false
    sort_pub_dependencies: false
    one_member_abstracts: false
    require_trailing_commas: false
    use_build_context_synchronously: false
    library_private_types_in_public_api: false
    avoid_positional_boolean_parameters: false

    # Obsolete with nnbd
    avoid_returning_null: false
