name: swift_travel
description: A new Flutter project.
publish_to: none

version: 1.0.1+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  live_route:
    path: dependencies/live_route/
  theming:
    path: ../utils/theming
  utils:
    path: ../utils/utils
  vibration:
    path: ../vibration
  android_intent: ^2.0.0-nullsafety.2
  animations: ^2.0.0-nullsafety.0
  async: ^2.4.2
  collection: ^1.15.0
  cupertino_icons: ^1.0.0
  file: ^6.0.0-nullsafety.4
  firebase_core: ^0.8.0-1.0.nullsafety
  firebase_crashlytics: ^0.5.0-1.0.nullsafety
  flex_color_scheme: ^2.0.0-nullsafety.1
  flutter_hooks: ^0.16.0-nullsafety.0
  flutter_riverpod: ^0.13.0-nullsafety.3
  flutter_slidable: ^0.6.0-nullsafety.0
  flutter_typeahead: ^3.0.0-nullsafety.0
  font_awesome_flutter: ^9.0.0-nullsafety
  freezed_annotation: ^0.13.0-nullsafety.0
  google_fonts: ^2.0.0-nullsafety.0
  hive: ^1.4.4+1
  intl: ^0.17.0-nullsafety.2
  json_annotation: ^4.0.0-nullsafety.0
  meta: ^1.3.0
  modal_bottom_sheet: ^2.0.0-nullsafety.1
  octo_image: ^1.0.0-nullsafety.1
  path_provider: ^2.0.0-nullsafety
  pedantic: ^1.10.0-nullsafety.3
  process_run: ^0.12.0-nullsafety.0
  quick_actions: ^0.5.0-nullsafety
  share: ^2.0.0-nullsafety.2
  shared_preferences: ^2.0.0-nullsafety
  shimmer: ^2.0.0-nullsafety.0
  url_launcher: ^6.0.0-nullsafety.1
  url_strategy: ^0.2.0-nullsafety.0

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.4
  freezed: ^0.13.0-nullsafety.2
  integration_test: ^1.0.1
  json_serializable: ^4.0.0-nullsafety.0
  lint: ^1.1.1
  mockito: ^5.0.0-nullsafety.1

dependency_overrides:
  freezed:
    git:
      url: https://github.com/gaetschwartz/freezed-1
      path: packages/freezed

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/profiles/
    - assets/anims/
    - assets/pictures/
    - assets/config.json
# flutter pub get
# flutter pub run flutter_launcher_icons:main
flutter_icons:
  ios: true
  android: false
  image_path: "assets/logo/swift-white.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/logo/swift.png"

flutter_intl:
  enabled: false
  use_deferred_loading: true
