name: playground
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  google_fonts:
  path:
  path_provider:
  swift_travel:
    path: ../../app
  theming:
    path: ../theming

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.5.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - packages/swift_travel/logo/swift.png
