name: Build

on:
  push:
    branches:
      - deploy

jobs:
  build-web:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    name: Build web
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Clone dependencies
        run: |
          git clone https://gaetschwartz:${{ secrets.ACCESS_TOKEN }}@github.com/gaetschwartz/utils.git
          git clone https://gaetschwartz:${{ secrets.ACCESS_TOKEN }}@github.com/vincenttarrit/vibration.git
        working-directory: ../
      - name: Get Flutter from cache
        uses: actions/cache@v2
        with:
          path: |
            /opt/hostedtoolcache/flutter
            $HOME/.pub-cache
          key: ${{ runner.OS }}-flutter-cache-${{ steps.release_json.outputs.json }}
      - name: Install Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: dev
      - name: Get git infos
        id: git-data
        run: |
          echo "::set-output name=hash::$(git rev-parse --short "$GITHUB_SHA")"
          echo "::set-output name=msg::$(git log -1 --pretty=format:"%s")"
          echo "::set-output name=count::$(git rev-list --count HEAD)"
      - name: Get dependencies
        run: |
          flutter config --enable-web
          flutter packages get
      - name: Pre-build configuration
        env:
          TZ: Europe/Zurich
          COMMIT_COUNT: ${{ steps.git-data.outputs.count }}
          GIT_MSG: ${{ steps.git-data.outputs.msg }}
          GIT_HASH: ${{ steps.git-data.outputs.hash }}
        run: bash CI/prebuild.sh
      - name: Build
        run: flutter build web --no-sound-null-safety
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_SWISS_TRAVEL_36188 }}"
          projectId: swiss-travel-36188
          channelId: live
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
